language: ruby
rvm:
  - 1.9.3
env: facebook_public_key=test facebook_private_key=test google_public_key=test google_private_key=test
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - darryqueen@berkeley.edu
      - edwhang@berkeley.edu
      - bwasmith@berkeley.edu
      - nalnaji@berkeley.edu
      - nishadsingh@berkeley.edu
      - jshum@berkeley.edu
