language: ruby
rvm:
- 1.9.3
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- bundle exec rake
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - darryqueen@berkeley.edu
    - edwhang@berkeley.edu
    - bwasmith@berkeley.edu
    - nalnaji@berkeley.edu
    - nishadsingh@berkeley.edu
    - jshum@berkeley.edu
before_install:
- openssl aes-256-cbc -K $encrypted_58e1943a8f8b_key -iv $encrypted_58e1943a8f8b_iv -in config/application.yml.enc -out config/application.yml -d
